### PR TITLE
Testing OTTR things

### PR DESCRIPTION
**Pull request by cansavvy**
### New Content Checklist

- [ ] New content/chapter is in an Rmd file with [this kind of format and headers](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/blob/main/02-chapter_of_course.Rmd).

- [ ] New content/chapter contains [Learning Objectives and are in the correct format](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/Setting-up-images-and-graphics#learning-objectives-formatting).

- [ ] [Bookdown successfully re-renders and any new content files have been added to the _bookdown.yml](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/Publishing-with-Bookdown).

- [ ] Spell check runs successfully in [Github actions style-n-check](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/How-to-set-up-and-customize-GitHub-actions-robots#spell-check)).

- [ ] Any newly necessary packages that are needed have been added to the [Dockerfile and image](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/Using-Docker#adding-packages-to-the-dockerfile).

- [ ] Images are in the [correct format for rendering](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/Setting-up-images-and-graphics#adding-images-and-graphics-in-text).

- [ ] Every new image has [alt text and is in a Google Slide](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/Setting-up-images-and-graphics#accessibility).

- [ ] Each slide is described in the notes of the slide so learners relying on a screen reader can access the content. See https://lastcallmedia.com/blog/accessible-comics for more guidance on this.

- [ ] The color palette choices of the slide are contrasted in a way that is friendly to those with color vision deficiencies.
You can check this using [Color Oracle](https://colororacle.org/).

### CODE REVIEW

**Comment by carriewright11** [comment]
@cansavvy I think we can close this now right?

**Comment by carriewright11** [comment]
hmmm although actually it still isn't updating the render

**Comment by cansavvy** [comment]
> hmmm although actually it still isn't updating the render

It looks updated? What is making you think it isn’t?

**Comment by carriewright11** [comment]
> > hmmm although actually it still isn't updating the render
> 
> It looks updated? What is making you think it isn’t?

The last thing I added was a disclaimer box in ch - history of ethics

**Comment by cansavvy** [comment]
> The last thing I added was a disclaimer box in ch -Data ethics - should be before 5.2.1: https://github.com/fhdsl/Ethical_Data_Handling_for_Cancer_Research/pull/80/files#diff-b79d8cefd2a7807734234b0813a0efa3d644798f64c2efb6af2d608a60194c70R67
> 
> and yet it is not here in the rendered version: https://hutchdatascience.org/Ethical_Data_Handling_for_Cancer_Research/data-ethics.html#after-considerations

This was just because the branch wasn't updated. The disclaimer box is there now so all looks to be working. Will close this PR.

**Comment by carriewright11** [comment]
> > The last thing I added was a disclaimer box in ch -Data ethics - should be before 5.2.1: https://github.com/fhdsl/Ethical_Data_Handling_for_Cancer_Research/pull/80/files#diff-b79d8cefd2a7807734234b0813a0efa3d644798f64c2efb6af2d608a60194c70R67
> > and yet it is not here in the rendered version: https://hutchdatascience.org/Ethical_Data_Handling_for_Cancer_Research/data-ethics.html#after-considerations
> 
> This was just because the branch wasn't updated. The disclaimer box is there now so all looks to be working. Will close this PR.

what I meant was ... I didn't see it in the main branch render

**Comment by carriewright11** [comment]
> > > The last thing I added was a disclaimer box in ch -Data ethics - should be before 5.2.1: https://github.com/fhdsl/Ethical_Data_Handling_for_Cancer_Research/pull/80/files#diff-b79d8cefd2a7807734234b0813a0efa3d644798f64c2efb6af2d608a60194c70R67
> > > and yet it is not here in the rendered version: https://hutchdatascience.org/Ethical_Data_Handling_for_Cancer_Research/data-ethics.html#after-considerations
> > 
> > 
> > This was just because the branch wasn't updated. The disclaimer box is there now so all looks to be working. Will close this PR.
> 
> what I meant was ... I didn't see it in the main branch render

so I don't see it here: https://hutchdatascience.org/Ethical_Data_Handling_for_Cancer_Research/data-ethics.html#after-considerations even though the PR that the change was on got merged: https://github.com/fhdsl/Ethical_Data_Handling_for_Cancer_Research/pull/80/files#diff-b79d8cefd2a7807734234b0813a0efa3d644798f64c2efb6af2d608a60194c70R6

**Pull request closed without merging**
